---
# example from https://www.youtube.com/watch?v=1xo-0gCVhTU and code from https://pastebin.com/rZa9Dm1w
kind: Service
apiVersion: v1
metadata:
  name: helloworldservicetest
spec:
  selector:
    app: hello-world
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 80
      # Port accessible outside cluster
      nodePort: 30001
  type: LoadBalancer
 
 
 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: tutm/hello-world
          ports:
            - containerPort: 80